spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  data:
    elasticsearch:
      hosts: ${ELASTICSEARCH_HOST-1}, ${ELASTICSEARCH_HOST-2}, ${ELASTICSEARCH_HOST-3}, ${ELASTICSEARCH_HOST-4}
      port: ${ELASTICSEARCH_PORT:9200}
